# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

target 'YZLibraryDemo' do

end

target 'YZLibraryDemoTests' do
  pod "Quick"
  pod "Nimble"
end

